# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  
  build:  
    docker:
      - image: cimg/node:lts
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ./.next/cache
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build && npm run export
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - out

  deploy-test:
      docker:
        - image: cimg/base:stable
      steps:
        - attach_workspace:
            at: /home/circleci/project
        - run: sudo apt-get update && sudo apt-get install -y lftp
        - run: cd out && lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME_TEST,$FTP_PASSWORD_TEST $FTP_HOST_TEST; mirror -R -e --delete-first --transfer-all . / --ignore-time --parallel=10"

  deploy-prod:
        docker:
          - image: cimg/base:stable
        steps:
          - attach_workspace:
              at: /home/circleci/project
          - run: sudo apt-get update && sudo apt-get install -y lftp
          - run: cd out && lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME_PROD,$FTP_PASSWORD_PROD $FTP_HOST_PROD; mirror -R -e --delete-first --transfer-all . / --ignore-time --parallel=10"

workflows:
  version: 2
  wf: 
    jobs:
      - build:
          filters:
            branches:
              only: 
                - test
                - master
      - deploy-test:
          requires:
            - build
          filters:
            branches:
              only: test
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
